import {
  Mouse,
  Keyboard,
  Headphones,
  Monitor,
  Laptop,
  Cpu,
  MousePointer2,
  Gamepad2,
  Tv,
  Smartphone,
  Tablet,
  HardDrive,
  Usb,
  Wifi,
  Mic,
  Camera,
  Printer,
  Server,
  Network,
  Database,
  Cloud,
  Shield,
  Lock,
  Key,
  User,
  Users,
  Settings,
  Home,
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  Trash2,
  Edit,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Loader2,
  RefreshCw,
  Download,
  Upload,
  Share2,
  Link2,
  ExternalLink,
  Mail,
  Phone,
  MapPin,
  Clock,
  Calendar,
  Star,
  Heart,
  Tag,
  Gift,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Banknote,
  Receipt,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,
  Folder,
  FolderOpen,
  Archive,
  Box,
  Package,
  Truck,
  Ship,
  Plane,
  Car,
  Bike,
  Bus,
  Train,
  Map,
  Navigation,
  Compass,
  Globe,
  Hash,
  AtSign,
  DollarSign,
  Euro,
  Bitcoin,
  Percent,
  TrendingUp,
  TrendingDown,
  BarChart,
  LineChart,
  PieChart,
  Activity,
  Zap,
  Battery,
  Power,
  WifiOff,
  Bluetooth,
  Volume2,
  VolumeX,
  Mic2,
  MicOff,
  CameraOff,
  MonitorOff,
  SmartphoneCharging,
  MousePointer,
  KeyboardOff,
  HardDriveDownload,
  HardDriveUpload,
  DatabaseBackup,
  ServerCog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  Moon,
  Sun,
  Droplet,
  Wind,
  Thermometer,
  Umbrella,
  Snowflake,
  Sunrise,
  Sunset,
} from 'lucide-react';

const defaultCategoryIcons = {
  'cat-mice': 'mouse',
  'cat-keyboards': 'keyboard',
  'cat-headsets': 'headphones',
  'cat-monitors': 'monitor',
  'cat-laptops': 'laptop',
  'cat-components': 'cpu',
  'cat-accessories': 'mouse-pointer-2',
};

const iconComponentMap = {
  mouse: Mouse,
  keyboard: Keyboard,
  headphones: Headphones,
  monitor: Monitor,
  laptop: Laptop,
  cpu: Cpu,
  'mouse-pointer-2': MousePointer2,
  gamepad2: Gamepad2,
  tv: Tv,
  smartphone: Smartphone,
  tablet: Tablet,
  'hard-drive': HardDrive,
  usb: Usb,
  wifi: Wifi,
  mic: Mic,
  camera: Camera,
  printer: Printer,
  server: Server,
  network: Network,
  database: Database,
  cloud: Cloud,
  shield: Shield,
  lock: Lock,
  key: Key,
  user: User,
  users: Users,
  settings: Settings,
  home: Home,
  search: Search,
  menu: Menu,
  x: X,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  plus: Plus,
  minus: Minus,
  'trash-2': Trash2,
  edit: Edit,
  eye: Eye,
  'eye-off': EyeOff,
  check: Check,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  'help-circle': HelpCircle,
  loader2: Loader2,
  'refresh-cw': RefreshCw,
  download: Download,
  upload: Upload,
  share2: Share2,
  link2: Link2,
  'external-link': ExternalLink,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  clock: Clock,
  calendar: Calendar,
  star: Star,
  heart: Heart,
  tag: Tag,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  banknote: Banknote,
  receipt: Receipt,
  'file-text': FileText,
  'file-image': FileImage,
  'file-video': FileVideo,
  'file-audio': FileAudio,
  'file-code': FileCode,
  folder: Folder,
  'folder-open': FolderOpen,
  archive: Archive,
  box: Box,
  package: Package,
  truck: Truck,
  ship: Ship,
  plane: Plane,
  car: Car,
  bike: Bike,
  bus: Bus,
  train: Train,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  hash: Hash,
  'at-sign': AtSign,
  'dollar-sign': DollarSign,
  euro: Euro,
  bitcoin: Bitcoin,
  percent: Percent,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  activity: Activity,
  zap: Zap,
  battery: Battery,
  power: Power,
  'wifi-off': WifiOff,
  bluetooth: Bluetooth,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'mic-2': Mic2,
  'mic-off': MicOff,
  'camera-off': CameraOff,
  'monitor-off': MonitorOff,
  'smartphone-charging': SmartphoneCharging,
  'mouse-pointer': MousePointer,
  'keyboard-off': KeyboardOff,
  'hard-drive-download': HardDriveDownload,
  'hard-drive-upload': HardDriveUpload,
  'database-backup': DatabaseBackup,
  'server-cog': ServerCog,
  'cloud-lightning': CloudLightning,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  moon: Moon,
  sun: Sun,
  droplet: Droplet,
  wind: Wind,
  thermometer: Thermometer,
  umbrella: Umbrella,
  snowflake: Snowflake,
  sunrise: Sunrise,
  sunset: Sunset,
};

const categoryGradients = {
  'cat-mice': 'grad-cat-mice',
  'cat-keyboards': 'grad-cat-keyboards',
  'cat-headsets': 'grad-cat-headsets',
  'cat-monitors': 'grad-cat-monitors',
  'cat-laptops': 'grad-cat-laptops',
  'cat-components': 'grad-cat-components',
  'cat-accessories': 'grad-cat-accessories',
  default: 'grad-cat-default',
};

function getCategoryIcon(category) {
  if (!category) return iconComponentMap.mouse;

  const iconKey = category.icon_key || defaultCategoryIcons[category.id] || defaultCategoryIcons[category.name?.toLowerCase().replace(/\s+/g, '-')];

  return iconComponentMap[iconKey] || iconComponentMap.mouse;
}

function getCategoryGradient(category) {
  if (!category) return `bg-${categoryGradients.default}`;

  return `bg-${categoryGradients[category.id] || categoryGradients[category.name?.toLowerCase().replace(/\s+/g, '-')] || categoryGradients.default}`;
}

function getAvailableIcons() {
  return Object.keys(iconComponentMap).sort();
}

function getDefaultCategoryIcons() {
  return { ...defaultCategoryIcons };
}

function getCategoryIconByName(name) {
  if (!name) return iconComponentMap.mouse;
  const key = name.toLowerCase().replace(/\s+/g, '-');
  const iconKey = defaultCategoryIcons[key] || defaultCategoryIcons[`cat-${key}`];
  return iconComponentMap[iconKey] || iconComponentMap.mouse;
}

export {
  defaultCategoryIcons,
  iconComponentMap,
  categoryGradients,
  getCategoryIcon,
  getCategoryGradient,
  getAvailableIcons,
  getDefaultCategoryIcons,
  getCategoryIconByName,
};